### ISSUE TITLE
Significant regression?  (appears to be related to new apropos feature)

### ISSUE THREAD

**Issue by dbadb** [ccrma/chuck#187] opened 2021-06-21 22:23 UTC
Important-seeming regression related to static class members (I think).

Through the magic of git bisect, it seems that the moment of bad is here:

0908327

ie: my test (attached) fails there, but not in the prior change: 90e0a3c

To run the test (from a console:  chuck main.ck (loads plot.ck and test.ck), then hangs out. (or crashes).

I've verified bad behavior on both windows and mac/bigsur.  

[_bug.zip](https://github.com/ccrma/chuck/files/6689785/_bug.zip)

**Comment by gewang** [comment] 2021-06-21 22:53
Great catch — working on this now...

**Comment by gewang** [comment] 2021-06-22 07:48
This bug report helpfully unearthed a number of issues related to the updated internal calling convention of static chuck functions, which now passes in a type reference. This has been addressed (hopefully successfully) in 3aca0006537e0daf59f70de2cbb3d6e4e1c8c57e and 45684256f7998b6efb07332172c668ba727c8d04.

If you'd like, could you verify the latter commit on your systems?  I'll leave this issue open until we have more confirmation.  I've also added a number of automated tests to catch related regressions in the future.  Thank you again for this timely bug report, as we plan to release 1.4.1.0 this week!

FYI Please note that these commits also includes incrementing Chugin major version number, which means any existing chugins will not load due to version mismatch (they need to be recompiled against the new header). The chugins repo (https://github.com/ccrma/chugins) has been updated to build against the latest headers. chuck-1.4.1.0 will ship with updated Chugins, but all 3rd-party Chugins will need to be re-compiled against the new headers to work with 1.4.1.0.

**Comment by dbadb** [comment] 2021-06-22 15:28
@gewang - I can happily confirm that we're back in business! My system is currently comprised of 87 or so public classes, many of which use static methods and members.
Great work to you and the ChucK team!

**Comment by gewang** [comment] 2021-06-22 17:56
@dbadb thank you for verifying and for the great catch/report in the first place! Closing this issue for now.

**Closed by gewang** 2021-06-22 17:56 UTC
